# MICROPROCESSOR-MICROCONTROLLER

ORG 0000H
SETB P1.0;       CONFIGURE PIN P1.0 
SETB P1.1;       CONFIGURE PIN P1.1 
SETB P1.2;       CONFIGURE PIN P1.2 
READ:MOV C,P1.0;  
JNC CKECK
SJMP READ
CHECK:MOV C,P1.1
JNC CHECK2
LJMP READ
CHECK:CLR P1.2
ACALL DELAY
SETB P1.2
LJMP READ
DELAY:MOV R7,#0X0FH
LOOP:DJNZ R7,LOOP
RET
END
